Traceback (most recent call last):
  File "/home/mike/Projects/python/venvs/jbook/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/mike/Projects/python/venvs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mike/Projects/python/venvs/jbook/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 172, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/mike/Projects/python/venvs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/mike/Projects/python/venvs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/mike/Projects/python/venvs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from glcd import glrplot 
import matplotlib.pyplot as plt

kappa=6
n=-1 # -1 give positive b field
a,b=0.001,3
for kappa in range(1,10):
  glrplot(kappa,n,a,b,f"\kappa={kappa}")

plt.subplot(1, 2, 1)
plt.xlabel("r")
plt.title(f"Vortex: f")
plt.legend()
plt.subplot(1, 2, 2)
plt.xlabel("r")
plt.title(f"Vortex: b")
plt.legend()
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mglcd[39;00m [38;5;28;01mimport[39;00m glrplot 
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m      4[0m kappa[38;5;241m=[39m[38;5;241m6[39m

[0;31mImportError[0m: cannot import name 'glrplot' from 'glcd' (/home/mike/Documents/github/glbook/practice/glcd.py)

